#!/bin/sh

killall sxhkd

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		3
bspc config window_gap			10
bspc config normal_border_color		"#4C566A"
bspc config focused_border_color	"#BF616A"

bspc config single_monocle		true
bspc config gapless_monocle		true
bspc config borderless_monocle		true
bspc config split_ratio			0.50

$HOME/.config/polybar/launch.sh
